<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>d2_motion</name>
  <version>0.0.1</version>
  <description>D2 집기·놓기(+ MoveIt2 실행기)와 장면 관리 노드</description>
  <maintainer email="pjy12110@gmail.com">박진용</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>d2_interfaces</exec_depend>
  <exec_depend>d2_safety</exec_depend>
  <exec_depend>d2_bringup</exec_depend>
  <exec_depend>dsr_msgs2</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
